server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://8.141.162.63:3306/odour?characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: XzzZyf
    password: XZZ!zyf@05240609
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # pagehelper

localImgPath: /usr/share/nginx/resource/
networkImgPath: resource/
staticAccessPath: /**


rawFileDir: /usr/share/nginx/resource/download/
teamNewsDir: /usr/share/nginx/resource/static/news/
