server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://172.22.0.2:3306/odourtest?characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 86129430Firstborn.
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: kecsun@163.com
    password: IIHSVMBMXJJSXRVE
    host: smtp.163.com
    properties:
      mail:
        smtp:
          auth: true
  servlet:
    multipart:
      max-file-size: 30MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#localImgPath: /usr/share/nginx/resource/
#networkImgPath: resource/
#staticAccessPath: /**
#
#
#rawFileDir: /usr/share/nginx/resource/download/
#teamNewsDir: /usr/share/nginx/resource/static/news/
#articleDir: /usr/share/nginx/resource/article/

localImgPath: /odour/resource/
networkImgPath: resource/
staticAccessPath: /**


rawFileDir: /odour/resource/download/
teamNewsDir: /odour/resource/static/news/
articleDir: /odour/resource/article/